name: todolist
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0
  path: ^1.8.0
  uuid: ^3.0.4
  intl: ^0.17.0
  sqflite_common_ffi: ^2.3.2+1
  sqlite3_flutter_libs: ^0.5.21


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  sqflite_common_ffi: ^2.3.2+1

flutter:
  uses-material-design: true
  assets:
    - lib/images/doit.png
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
